### ISSUE TITLE
deepseq 1.4 support

### ISSUE THREAD

**Issue by snoyberg** [nominolo/atto-lisp#18]
This is currently blocking Stackage from moving to GHC 7.10. Would you be able to relax the upper bound?

**Comment by snoyberg** [comment]
Bump, a Stack user just complained about this due to wanting to use present (so also pinging @chrisdone).

**Comment by nominolo** [comment]
I thought the version on hackage was edited. I just fixed the repo version,
but I don't have my hackage password available right now. If someone here
is a Hackage admin, feel free to upload version 0.2.2.1 to Hackage.
Otherwise, I'll do it this evening (CEST).

**Comment by nominolo** [comment]
0.2.2.1 is on Hackage now.

**Comment by snoyberg** [comment]
Thanks!
