### ISSUE TITLE
build error (GHC 6.12.3)

### ISSUE THREAD

**Issue by kowey** [nominolo/atto-lisp#4]
Hi Thomas,

One of my users reports the following build error with GHC 6.12.3.  Do you think it's an easy fix?  Thanks! :-)

    Data/AttoLisp.hs:1:0:
        Couldn't match expected type `c' against inferred type `b'
          `c' is a rigid type variable bound by
              the instance declaration at Data/AttoLisp.hs:308:34
          `b' is a rigid type variable bound by
              the instance declaration at Data/AttoLisp.hs:308:32
        When using functional dependencies to combine
          ParseList b b,
            arising from a use of `parseList' at Data/AttoLisp.hs:312:4-25
          ParseList b c,
            arising from the instance declaration at Data/AttoLisp.hs:308:9-59
    
    Data/AttoLisp.hs:309:2:
        Couldn't match expected type `c' against inferred type `b'
          `c' is a rigid type variable bound by
              the instance declaration at Data/AttoLisp.hs:308:34
          `b' is a rigid type variable bound by
              the instance declaration at Data/AttoLisp.hs:308:32
        When using functional dependencies to combine
          ParseList a a,
            arising from the dependency `a -> b'
            in the instance declaration at Data/AttoLisp.hs:314:9
          ParseList b c,
            arising from a use of `parseList' at Data/AttoLisp.hs:312:4-25
        When generalising the type(s) for `parseList'
        In the instance declaration for `ParseList (a -> b) c'
    
    Data/AttoLisp.hs:312:4:
        Overlapping instances for ParseList b b
          arising from a use of `parseList' at Data/AttoLisp.hs:312:4-25
        Matching instances:
          instance ParseList a a -- Defined at Data/AttoLisp.hs:314:9-21
          instance (FromLisp a, ParseList b c) => ParseList (a -> b) c
            -- Defined at Data/AttoLisp.hs:308:9-59
        (The choice depends on the instantiation of `b'
         To pick the first instance above, use -XIncoherentInstances
         when compiling the other instance declarations)
        In the expression: parseList msg (f y) xs
        In the expression:
            do { y <- parseLisp x;
                 parseList msg (f y) xs }
        In the definition of `parseList':
            parseList msg f (x : xs)
                        = do { y <- parseLisp x;
                               parseList msg (f y) xs }
    cabal: Error: some packages failed to install:
    atto-lisp-0.2 failed during the building phase. The exception was:
    ExitFailure 1

**Comment by nominolo** [comment]
Closing, because 6.12 is no longer supported.
